### ISSUE TITLE
awot-static: Platform.io compatibility

### ISSUE THREAD

**Issue by jgibbon** [lasselukkari/awot-scripts#98]
Hi @lasselukkari,
first of all: being a beginner with embedded development, I am really impressed with awot. A quick test with a vue web app on an esp32 was a lot faster than other solutions for me. Really good job!

I have a problem including the awot-static header file using Platform.io as an IDE, though. 
Due to the way it [resolves includes](https://docs.platformio.org/en/latest/librarymanager/ldf.html#ldf), used header files seem to be included multiple times, so I'm getting a lot of "multiple definition" errors when including `StaticFiles.h` even once.

It works when I manually copy the contents into a .cpp file used to initialize the web server, but that's quite a bit cumbersome.

Do you think an optional "class mode" in awot-static could be useful for this?

I'm (_again, bloody beginner, there may be many bad ideas in here_) thinking along the lines of an output like this:

**StaticFiles.h:**
```
#ifndef _STATICFILES_H_
#define _STATICFILES_H_
#include <aWOT.h>

P(static_index_0) = { […] };
P(static_css_app_css_0) = { […] };


class StaticFiles {
private:
  static void static_index (Request &req, Response &res);
  static void static_css_app_css (Request &req, Response &res);
public:
  static Router * staticFiles();
};

#endif //_STATICFILES_H_
```
**StaticFiles.cpp:**
```
#include "StaticFiles.h";

void StaticFiles::static_index (Request &req, Response &res) {
  res.set("Content-Type", "text/html; charset=utf-8");
[…]

  res.writeP(static_index_0, 1234);
}

void StaticFiles::static_css_app_css (Request &req, Response &res) {
  res.set("Content-Type", "text/css; charset=utf-8");
[…]

  res.writeP(static_css_app_css_0, 1234);
}

Router staticFileRouter;

Router * StaticFiles::staticFiles(){
  staticFileRouter.get("/", &StaticFiles::static_index);
  staticFileRouter.get("/css/app.css", &StaticFiles::static_css_app_css);
  return &staticFileRouter;
}
```
which could then be simply used with `app.use(StaticFiles::staticFiles());` after including the header – even in Platform.io, which I've tried manually. The naming in my example isn't optimal, I know. ;)

Thanks for taking the time to read this!

cheers,
John

**Comment by lasselukkari** [comment]
Hi! Thanks for reporting the problem. I personally have not used platformio that much but I have a few users that do and they have not had issues as far as I know. @ArminPP any ideas what could be happening here? Have you encountered this? I do have one project where I use it for building the project as CI step here: https://github.com/lasselukkari/DuinoDCX.

I definitely want to support platformio in this project so this is something that needs to be fixed if there is a problem. I will try to reproduce this soon.

**Comment by ArminPP** [comment]
I'm also really new to all of this stuff too, but since I'm trying to learn aWot, I'm working with PlatformIO.
Based on the BlinkServer.ino project, everything still works like a charm. I never had problems including StaticFiles.h in PIO.

best greetings Armin

**Comment by jgibbon** [comment]
Hi all,
thanks for your feedback – ideally I just did it wrong. 
I'll try to create a tiny platformio project to try and/or reproduce this without much overhead the next days.

cheers!

**Comment by moesterheld** [comment]
Maybe I can help.

I am using (the excellent ;-)) awot with PlatformIO in the following way:
- create boilerplate code in frontend using _awot-create_
- set up your PlatformIO project
- integrate the _.ino_ boilerplate code into your _src/main.cpp_
- create a _awot_ directory in the PlatformIO lib directory and move generated _.cpp_ and _.h_ files there
- configure _awot-static_ to create static files in the lib directory in future builds, e.g. (the important part being the sketchDir)
```
"awot-static": {
    "sources": "./dist",
    "indexFile": "index.html",
    "sketchDir": "../board/lib/awot",
    "sdCard": false,
    "exclude": [
      "*.map",
      "service-worker.js"
    ]
  }
```

I like to use a directory structure where I have the PlatformIO Project (board in my case) next to the frontend code, not in a subdirectory as in the tutorial.

**Comment by lasselukkari** [comment]
> I like to use a directory structure where I have the PlatformIO Project (board in my case) next to the frontend code, not in a subdirectory as in the tutorial.

I agree that this is better. I have been planning to update the tutorial to follow this directory structure too.

**Comment by jgibbon** [comment]
Hi all,
thanks again for your great input! 
Having sibling directories for front end/back end sounds like a good, maintainable plan for a project structure.

I'm sorry to have wasted your time with this, but on the other hand I'm glad it was my error (or an "opportunity to learn"?) after all:
The described problem was solved by just including the generated .h from a .cpp file instead of the corresponding .h. Yes, it was this simple. I really should've seen that tonight already without bothering you all.

So even I can now confirm that awot works beautifully inside platformio already, no need for the proposed workaround. 

Another small note @lasselukkari – I've noticed the awot version inside the [platformio registry](https://platformio.org/lib/show/6333/aWOT/) hasn't been updated recently.

cheers!

**Comment by lasselukkari** [comment]
No need to be sorry. Good that you got it working.

> Another small note @lasselukkari – I've noticed the awot version inside the [platformio registry](https://platformio.org/lib/show/6333/aWOT/) hasn't been updated recently.

Thanks for reporting this. 

And a big thank you to @moesterheld and @ArminPP for helping to solve this.

**Comment by lasselukkari** [comment]
@jgibbon the platformio package should now be updated.
